# Generated by Django 3.2.8 on 2021-11-28 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название месторождения')),
                ('x_coordinate', models.FloatField(max_length=10, verbose_name='Координата Х')),
                ('y_coordinate', models.FloatField(max_length=10, verbose_name='Координата Y')),
                ('reservoir_age', models.PositiveBigIntegerField(verbose_name='Возраст залежи')),
                ('formation_saturation', models.FloatField(max_length=10, verbose_name='Координата Y')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название организации')),
                ('amount_of_workers', models.IntegerField(verbose_name='Количество сотрудников')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание организации')),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя скважины')),
                ('purpose', models.CharField(max_length=255, verbose_name='Назначение скважины')),
                ('drilling_mud', models.CharField(max_length=255, verbose_name='Буровой раствор')),
                ('profile', models.CharField(max_length=255, verbose_name='Профиль')),
                ('sank_amount', models.IntegerField(verbose_name='Количество стволов')),
                ('drilling_cost', models.FloatField(max_length=25, verbose_name='Стоимость бурения')),
                ('developing_cost', models.FloatField(max_length=25, verbose_name='Стоимость освоения')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='core.field')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, verbose_name='Статус')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('downtime', models.FloatField(max_length=10, verbose_name='Время простоя')),
                ('reason', models.CharField(max_length=255, verbose_name='Причина простоя')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_notes', to='core.well')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='core.organisation'),
        ),
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата внесения информации')),
                ('oil_output', models.FloatField(max_length=100, verbose_name='Добыча нефти')),
                ('gas_output', models.FloatField(max_length=100, verbose_name='Добыча газа')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_notes', to='core.well')),
            ],
        ),
    ]
