# Generated by Django 3.2.8 on 2022-02-21 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название схемы')),
            ],
        ),
        migrations.AlterModelOptions(
            name='extraction',
            options={'verbose_name': 'Добыча скважины', 'verbose_name_plural': 'Добычи скважин'},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': 'Месторождение', 'verbose_name_plural': 'Месторождения'},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Состояние скважины', 'verbose_name_plural': 'Состояния скважин'},
        ),
        migrations.AlterModelOptions(
            name='well',
            options={'verbose_name': 'Скважина', 'verbose_name_plural': 'Скважины'},
        ),
        migrations.AlterField(
            model_name='extraction',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_notes', to='core.well', verbose_name='Скважина'),
        ),
        migrations.AlterField(
            model_name='field',
            name='formation_saturation',
            field=models.FloatField(max_length=10, verbose_name='Насыщенность залежи'),
        ),
        migrations.AlterField(
            model_name='field',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='core.organisation', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='state',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_notes', to='core.well', verbose_name='Скважина'),
        ),
        migrations.AlterField(
            model_name='well',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='core.field', verbose_name='Месторождение'),
        ),
        migrations.CreateModel(
            name='ImportSchemaAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_position', models.PositiveIntegerField(verbose_name='Количество стволов')),
                ('type_name', models.CharField(max_length=255, verbose_name='Название cвязываемой модели')),
                ('attr_name', models.CharField(max_length=255, verbose_name='Атрибут')),
                ('import_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='core.importschema', verbose_name='Схема импорта')),
            ],
        ),
    ]
