# Generated by Django 3.2.8 on 2022-02-21 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_auto_20220221_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importschema',
            options={'verbose_name': 'Схема импорта', 'verbose_name_plural': 'Схемы импорта'},
        ),
        migrations.AlterModelOptions(
            name='importschemaattribute',
            options={'verbose_name': 'Атрибут схемы импорта', 'verbose_name_plural': 'Атрибуты схемы импорта'},
        ),
        migrations.AddField(
            model_name='importschema',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importschema',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='importschemaattribute',
            name='column_position',
            field=models.PositiveIntegerField(verbose_name='Номер столбца'),
        ),
    ]
