# Generated by Django 3.2.8 on 2022-04-08 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220403_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellstate',
            name='bottom_hole_pressure',
        ),
        migrations.RemoveField(
            model_name='wellstate',
            name='esp_current',
        ),
        migrations.RemoveField(
            model_name='wellstate',
            name='esp_frequency',
        ),
        migrations.RemoveField(
            model_name='wellstate',
            name='esp_pressure',
        ),
        migrations.RemoveField(
            model_name='wellstate',
            name='formational_pressure',
        ),
        migrations.RemoveField(
            model_name='wellstate',
            name='gas_rate',
        ),
        migrations.RemoveField(
            model_name='wellstate',
            name='liquid_rate',
        ),
        migrations.RemoveField(
            model_name='wellstate',
            name='oil_rate',
        ),
        migrations.RemoveField(
            model_name='wellstate',
            name='pump_parameters_measurement_date',
        ),
        migrations.AddField(
            model_name='wellextraction',
            name='bottom_hole_pressure',
            field=models.FloatField(default=0, max_length=50, verbose_name='Забойное давление'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellextraction',
            name='gas_rate',
            field=models.FloatField(default=0, max_length=50, verbose_name='Дебит газа, м3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellextraction',
            name='liquid_rate',
            field=models.FloatField(default=0, max_length=50, verbose_name='Дебит жидкости, м3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellextraction',
            name='oil_rate',
            field=models.FloatField(default=0, max_length=50, verbose_name='Дебит нефти, т'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wellextraction',
            name='gas_injection',
            field=models.FloatField(max_length=50, verbose_name='Закачка газа'),
        ),
        migrations.AlterField(
            model_name='wellextraction',
            name='gas_output_m3',
            field=models.FloatField(max_length=50, verbose_name='Добыча газа, тыс м3'),
        ),
        migrations.AlterField(
            model_name='wellextraction',
            name='water_injection',
            field=models.FloatField(max_length=50, verbose_name='Закачка воды'),
        ),
        migrations.CreateModel(
            name='PumpParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_parameters_measurement_date', models.DateField(verbose_name='Дата измерения параметров насоса')),
                ('esp_frequency', models.FloatField(max_length=50, verbose_name='Частота ЭЦН')),
                ('esp_pressure', models.FloatField(max_length=50, verbose_name='Напор ЭЦН')),
                ('esp_current', models.FloatField(max_length=50, verbose_name='Ток ЭЦН')),
                ('well', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pump_parameters', to='core.well', verbose_name='Скважина')),
            ],
            options={
                'verbose_name': 'Насос',
                'verbose_name_plural': 'Насосы',
            },
        ),
    ]
