# Generated by Django 3.2.8 on 2022-05-14 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220427_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='x_coordinate',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='y_coordinate',
        ),
        migrations.RemoveField(
            model_name='well',
            name='owner',
        ),
        migrations.AddField(
            model_name='cluster',
            name='max_deflection_of_borehole',
            field=models.FloatField(default=0, max_length=50, verbose_name='Максимальное отклонение забоя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Аббревиатура'),
        ),
        migrations.AddField(
            model_name='field',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wells', to='core.organisation', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='pumpparameters',
            name='pump_type',
            field=models.CharField(default='default', max_length=255, verbose_name='Вид насоса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well',
            name='x_coordinate',
            field=models.FloatField(default=0, max_length=50, verbose_name='Координата Х'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well',
            name='y_coordinate',
            field=models.FloatField(default=0, max_length=50, verbose_name='Координата Y'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coresample',
            name='well',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_samples', to='core.well', verbose_name='Скважина'),
        ),
    ]
