# Generated by Django 3.2.8 on 2022-05-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220515_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='formation_volume_factor_for_oil',
            field=models.FloatField(default=0, max_length=50, verbose_name='Объемный коэффициент нефти'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='formation_volume_factor_for_water',
            field=models.FloatField(default=0, max_length=50, verbose_name='Объемный коэффициент воды'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='gas_density',
            field=models.FloatField(default=0, max_length=50, verbose_name='Плотность газа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='gas_dynamic_viscosity',
            field=models.FloatField(default=0, max_length=50, verbose_name='Динамическая вязкость газа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='gas_factor',
            field=models.FloatField(default=0, max_length=50, verbose_name='Газовый фактор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='oil_density',
            field=models.FloatField(default=0, max_length=50, verbose_name='Плотность нефти'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='oil_dynamic_viscosity',
            field=models.FloatField(default=0, max_length=50, verbose_name='Динамическая вязкость нефти'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='water_density',
            field=models.FloatField(default=0, max_length=50, verbose_name='Плотность воды'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='water_dynamic_viscosity',
            field=models.FloatField(default=0, max_length=50, verbose_name='Динамическая вязкость воды'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well',
            name='layers',
            field=models.ManyToManyField(blank=True, related_name='wells', to='core.Layer', verbose_name='Пласты'),
        ),
        migrations.AlterUniqueTogether(
            name='well',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='FluidProperties',
        ),
        migrations.RemoveField(
            model_name='well',
            name='layer',
        ),
    ]
