# Generated by Django 3.2.8 on 2022-05-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220521_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='formation_volume_factor_for_oil',
            field=models.FloatField(max_length=50, null=True, verbose_name='Объемный коэффициент нефти'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='formation_volume_factor_for_water',
            field=models.FloatField(max_length=50, null=True, verbose_name='Объемный коэффициент воды'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='gas_density',
            field=models.FloatField(max_length=50, null=True, verbose_name='Плотность газа'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='gas_dynamic_viscosity',
            field=models.FloatField(max_length=50, null=True, verbose_name='Динамическая вязкость газа'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='gas_factor',
            field=models.FloatField(max_length=50, null=True, verbose_name='Газовый фактор'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='oil_density',
            field=models.FloatField(max_length=50, null=True, verbose_name='Плотность нефти'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='oil_dynamic_viscosity',
            field=models.FloatField(max_length=50, null=True, verbose_name='Динамическая вязкость нефти'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='water_density',
            field=models.FloatField(max_length=50, null=True, verbose_name='Плотность воды'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='water_dynamic_viscosity',
            field=models.FloatField(max_length=50, null=True, verbose_name='Динамическая вязкость воды'),
        ),
    ]
