# Generated by Django 3.2.8 on 2022-06-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220524_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumpparameters',
            name='pump_state',
            field=models.CharField(default='default', max_length=255, verbose_name='Состояние насоса'),
            preserve_default=False,
        ),
    ]
